### ISSUE TITLE
Users with no display name set show up as "null"

### ISSUE THREAD

**Issue by RUvlad1** [gtrxAC/discord-j2me#1]
pretty self-explanatory

What shows up on Discord J2ME
![image](https://github.com/gtrxAC/discord-j2me/assets/60317461/8f102ff3-3880-4048-ada2-b67d55aaa9db)

How it should be
![image](https://github.com/gtrxAC/discord-j2me/assets/60317461/7b7eb21d-cd4f-4d9e-8637-3fab5070eedd)

![image](https://github.com/gtrxAC/discord-j2me/assets/60317461/fc05d0f2-cadb-4536-95c4-b27730715d95)

**Comment by gtrxAC** [comment]
Fixed in version 1.1.0.
