### ISSUE TITLE
i dont know how to do it

### ISSUE THREAD

**Issue by 09er9** [gtrxAC/discord-j2me#10]
i've got 7 phones capable of running this but i dont understand how to do it, if somebody can give me like a step to step guide or something that would be really helpful

**Comment by sunflowers33d** [comment]
click the releases tab to download the JAR, put it on your phones of choice and run it. then you will need to get your discord token (search on your favorite search engine) and type it in discord-j2me

**Comment by 09er9** [comment]
alright thanks

**Comment by 09er9** [comment]
do i transfer via usb or directly install it?

**Comment by R0ci0-V3rd3al** [comment]
you need to obtain the token with the "dev tools" tool that comes by default in your browser with chrome

**Comment by R0ci0-V3rd3al** [comment]
install via bluetooth or download via the browser....it's not difficult

**Comment by 09er9** [comment]
im gonna try putting it from my pc to my s7 edge to my nokia n8

**Comment by 09er9** [comment]
this might actually just be a cable issue

**Comment by 09er9** [comment]
YESSS IT WORKED WITH BLUETOOTH LETS GOO

**Comment by 09er9** [comment]
now how do i get the token with dev tools

**Comment by 09er9** [comment]
bruh it doesnt wanna load the website anymore

**Comment by 09er9** [comment]
do i have to use that website or can i just use discord itself

**Comment by speedyes** [comment]
https://letmegooglethat.com/?q=how+to+get+discord+token+pc
bro it's not that hard to google it yourself. try everything until it works eventually
