### ISSUE TITLE
Unable to view JPG image attachments on Symbian S60v3

### ISSUE THREAD

**Issue by matu6968** [gtrxAC/discord-j2me#13]
I was messing around with the new update when i saw it supported image attachments, so decided to give a shot on my Nokia N82 but found out disappointed when it couldn't load a JPG image with it saying (no data) and it gives out one time every app restart a "Unsupported exception. Close app?" prompt. 

![20240617_205024.jpg](https://github.com/gtrxAC/discord-j2me/assets/89382946/d433b5d6-874c-47ee-8895-ab815a1dfac7)

Other formats used: PNG, GIF (these work no problem)

**Comment by gtrxAC** [comment]
Seems like recently our Discord CDN (image server) proxy stopped accepting `width` and `height` parameters in the image download URLs, causing the images to be downloaded in full resolution.

However (I didn't realize this either until now) you can actually use the official Discord CDN (media.discordapp.net, but not cdn.discordapp.com) via non-secure HTTP connections - so try setting your CDN URL to `http://media.discordapp.net`.

**Comment by matu6968** [comment]
> However (I didn't realize this either until now) you can actually use the official Discord CDN (media.discordapp.net, but not cdn.discordapp.com) via non-secure HTTP connections (i.e. old phones) - so try setting your CDN URL to `http://media.discordapp.net`.

Tried it out and sure enough it didn't cause a error again and actually displayed images normally albeit a bit not fully utilizing the phone's screen for it so that it can be zoomed for better viewing cause it's a bit unreadable as is, that means it is indeed a CDN issue ![image](https://github.com/gtrxAC/discord-j2me/assets/89382946/30c59fc6-eab9-421c-8b9d-f580ed4bf988)

**Comment by matu6968** [comment]
issue seems to be fixed anyways so closing issue
