### ISSUE TITLE
Strange http 502 error 

### ISSUE THREAD

**Issue by Turev-Hunter** [gtrxAC/discord-j2me#14]
Application is doesn't connect to servers its always display http 502 error and after next attempt display an java error: java.lang.NullPointerException:0 how can I fix this.
Ps: app working on an old s60v2 phone

**Comment by matu6968** [comment]
It seems like it is a proxy issue as it also happened on my Nokia Asha 206.

**Comment by gtrxAC** [comment]
Yes, this is a proxy issue. For now, you can use the alternative proxy `http://57.128.194.14` (without the :8087 at the end), though note that it will be slower than the default proxy.
