### ISSUE TITLE
Unable to type in full token on Blackberry 9900

### ISSUE THREAD

**Issue by joelis10** [gtrxAC/discord-j2me#17]
_Ignore the first version of this message_
For obvious reasons I'm not going to show my full token here, but essentially the issue is that the token field on the login page on my BB 9900 is limited and I can only type around a quarter of it before running out of space. I originally thought it was the last two characters I couldn't type but then looked at it closer and realised it was a lot more than that. Did I get the wrong token or is this a BB issue?

**Comment by itskme** [comment]
I think you have the wrong token. I am using a 9900 and the token was almost exactly two lines for me. I followed this tutorial to get it: https://www.howtogeek.com/879956/what-is-a-discord-token-and-how-do-you-get-one/

hope this helps!

**Comment by joelis10** [comment]
Yeah soon after posting the issue, I realised that and forgot to close. Closing now.
