### ISSUE TITLE
Compiling issue - missing 'javac'

### ISSUE THREAD

**Issue by tdp2612** [gtrxAC/discord-j2me#2]
Setting up directories
Compiling
discord-j2me-main/build.sh: line 13: sdk/jdk1.6.0_45/bin/javac: No such file or directory

is the error I get, but when I look in the director there I find javac.exe along with many other files. Am I doing something silly like using the wrong Java install file, maybe this being a Windows one has something to do with it?

**Comment by tdp2612** [comment]
Just tried with the Linux 64 bit version, now it has javac (no extension) where it should be, still getting the same error. A bit confused now.

**Comment by gtrxAC** [comment]
The build script is designed for Linux. It seems like you ran the build script outside the repo's root directory, which is why it doesn't find the sdk folder. Switch to the discord-j2me-main directory and run ./build.sh, then it should work.

**Comment by tdp2612** [comment]
Thanks for the help, I'm one step closer now - I get an error for Java not being installed or something, tried uninstalling the modern version and installing both 32 and 64 bit windows versions. 
![image](https://github.com/gtrxAC/discord-j2me/assets/168689662/b6743172-33a3-4d14-90af-49d33651eb5e)

I have a machine running Ubuntu in the attic, I'll give it a try on that and see if it helps at all.

**Comment by gtrxAC** [comment]
I have not seen that error before. If you're still interested, see if [this](https://stackoverflow.com/questions/11808829/jre-1-7-java-version-returns-java-lang-noclassdeffounderror-java-lang-obje) helps. Did it work any better on Ubuntu?

**Comment by tdp2612** [comment]
Thank you for the reply and the continued attempts to help. I still havent tested on Ubuntu, I couldnt find the power supply for the weird old office box I had it on, couldn't do it on a laptop because both are dead apparently, and my main PC just wasnt having it, wouldnt boot. I'm going to hold off for now til I find the power supply, it should be somewhere, and then I'm kinda expecting it to just work. I don't think Windows bash is the way to go, you've intended this for Linux of some type, so thats what I should use.

**Comment by gtrxAC** [comment]
Finally got around to porting the build script to Windows - it should compile on Windows now. Apparently Proguard refuses to run on the old JDK on Windows, so you'll need two JDK installations to build the app.
