### ISSUE TITLE
Feature request: add color to names (only in servers, if the role has a color other then white)

### ISSUE THREAD

**Issue by matu6968** [gtrxAC/discord-j2me#20]
On the official client, if the user has a role that has a color attached to it then display the color on the client just like the official one does.

Role ID's are similar to user ID's like this: (api request example showing roles in a server)
`{
    "1250537996768510065": 1, - red color aka owner
    "1250533563204632586": 1, - green color aka admin
    "1250534494629400818": 1, - rose pink aka maintainer
}`

each user color seems to be handled either by JavaScript code or another API request so it may prove a challenge to make it work.

**Comment by gtrxAC** [comment]
Already implemented. To see name colors, enable gateway connection ("Use gateway" in login screen) and enable "Show name colors" in settings.
