### ISSUE TITLE
client stopped working on S60v3

### ISSUE THREAD

**Issue by matu6968** [gtrxAC/discord-j2me#21]
In previous versions (last tested on 2.1.0) logging in worked but even since 3.x.x it refuses it work (tried all send token as options, none of them work) and also the token is valid as I tried on other devices and it worked without a issue so another Symbian related issue or something odd going on. ![image](https://github.com/user-attachments/assets/ccef6101-8dae-44bd-9fb1-a50890e38010)

**Comment by gtrxAC** [comment]
Can you try uninstalling and reinstalling the app?

**Comment by matu6968** [comment]
Turns out i messed up the token, apologies for the issue.
