### ISSUE TITLE
Feature Request and Some Bugs Nokia 303

### ISSUE THREAD

**Issue by HamzaYslmn** [gtrxAC/discord-j2me#24]
Is there a solution to not receive notifications or is there such a feature?

Notification does not work with nokia 303.

I am using V3 MIDP 2.0

**Comment by HamzaYslmn** [comment]
Phone OS version: RM-763

**Comment by HamzaYslmn** [comment]
Now ı can send photo with uncheck native file picker

**Comment by HamzaYslmn** [comment]
Gateway fixes the live chat.

Now ı just need notification

**Comment by HamzaYslmn** [comment]
I ask to chatgpt, idk java coding. But maybe this helps:



To address the issues with the Nokia 303 not showing notifications, vibration not working, and the lack of an option to keep the app running in the background, you need to modify your Java ME code accordingly. Here’s how you can approach these issues:

### 1. **Enable Notifications:**
   - **PushRegistry**: To ensure your app can continue to run and receive notifications in the background, you can register your app with `PushRegistry`. This allows your app to be automatically started when certain events occur, like receiving a message or notification.

   - **Notification Handling**: Ensure that your app is properly handling notifications using the `Alert` class or custom UI elements to display notifications when they occur.

### 2. **Enable Vibration:**
   - Use the `AlertType` class to trigger device vibrations. Specifically, you can use `AlertType.ALARM.playSound(Display.getDisplay(this));` or `DeviceControl.startVibra(int duration)` to make the device vibrate.

### 3. **Keep App Running in the Background:**
   - **Background Processing**: Use `MIDlet.notifyPaused()` to pause the app while it continues to run in the background. Also, make sure your app can handle resuming from the paused state by overriding `startApp()` to restore state if necessary.

### Example Code Modifications

Here’s how you could modify parts of your code to incorporate these changes. Let's assume you're working with the `DiscordMIDlet` class, which is the entry point for your application:

#### **Start App with PushRegistry**
Add code to register for push notifications and start your app in the background:

```java
import javax.microedition.io.PushRegistry;
import javax.microedition.midlet.*;

public class DiscordMIDlet extends MIDlet {
    private boolean started = false;
    private static State s;

    public DiscordMIDlet() {
        started = false;
    }

    public void startApp() {
        if (!started) {
            s = new State();
            s.midlet = this;
            s.disp = Display.getDisplay(this);

            // Check for any pending alarms or push notifications
            String[] connections = PushRegistry.listConnections(true);
            if (connections != null && connections.length > 0) {
                // Handle the push connection
            }

            boolean haveLoginRms = true;
            try {
                RecordStore.openRecordStore("login", false).closeRecordStore();
            } catch (Exception e) {
                haveLoginRms = false;
            }

            if (!haveLoginRms && getAppProperty("Token") == null) {
                s.disp.setCurrent(new LoginForm(s));
            } else {
                LoginSettings.load(s);
                s.login();
            }

            started = true;
        }
    }

    public void pauseApp() {
        // Keep app running in the background
        notifyPaused();
    }

    public void destroyApp(boolean unconditional) {}
}
```

#### **Handle Vibration**
To trigger vibration when a notification is received or when an alert is shown:

```java
import javax.microedition.lcdui.Alert;
import javax.microedition.lcdui.AlertType;

public class NotificationHandler {
    
    public void showNotification(String message) {
        Alert alert = new Alert("Notification", message, null, AlertType.ALARM);
        alert.setTimeout(Alert.FOREVER);
        
        // Trigger vibration
        AlertType.ALARM.playSound(Display.getDisplay(midlet));
        
        Display.getDisplay(midlet).setCurrent(alert);
    }
}
```

#### **Handle Background Operations**
Ensure your app can handle being in the background and properly manage its state:

```java
public void startApp() {
    if (getAppProperty("MIDlet-Background") != null) {
        // Code to resume from background
        restoreAppState();
    } else {
        // Normal start-up code
        initializeApp();
    }
}

public void pauseApp() {
    saveAppState();
    notifyPaused();  // Ensure the app continues running in the background
}

public void destroyApp(boolean unconditional) {
    saveAppState();
}

private void saveAppState() {
    // Save necessary app state before going into background or being destroyed
}

private void restoreAppState() {
    // Restore the app state when resuming from the background
}
```

### Summary
1. **Enable notifications** using `PushRegistry`.
2. **Enable vibration** for alerts using `AlertType`.
3. **Manage app background behavior** using `notifyPaused()` and state management.

By implementing these changes, your app on the Nokia 303 should handle notifications, enable vibration, and allow background operation effectively.

**Comment by HamzaYslmn** [comment]
<img width="24" alt="tbjhgqpc2nn61" src="https://github.com/user-attachments/assets/ba60c65c-09f2-44c7-9479-9fab543c175d">
Retro Discord İcon

**Comment by HamzaYslmn** [comment]
<img width="192" alt="tbjhgqpc2nn61 - Kopya" src="https://github.com/user-attachments/assets/8fac0012-52a6-4f53-b6fa-740bd742e499">

Loading animation

**Comment by gtrxAC** [comment]
I'm not sure if PushRegistry will work for this, but I have an idea for adding notification support to the app (sort of). On newer Symbian phones, it is possible to have system-level notifications via an extension API (Pigler). On some other phones, the app can stay running in the background, receiving messages via the gateway, and then show alert messages for notifications. I plan to add one or both of these notification systems at some point, but I'm working on other features right now.

I already have a loading animation implemented, which will be available in the next update (3.1 or 4.0).

**Comment by HamzaYslmn** [comment]
a great project, I wish I knew java, I would like to help...

In 2024 on my “Nokia Asha 303, s40” there was no application to chat over the internet.
It was really water in the desert for me.

If you can fix the notification problem, I won't expect much more. 
Thank you very much...

**Comment by HamzaYslmn** [comment]
I don't know if I can run the app in the background on my nokia 303, but it would be sweet if it would at least vibrate and light up when I lock the screen with the app open.

**Comment by gtrxAC** [comment]
Version 4.0 is releasing in a few days, which will include notification support. Vibration/light-up support may be added later.
