### ISSUE TITLE
Getting RuntimeException: Blocking call performed in the event thread.

### ISSUE THREAD

**Issue by e3ndr** [gtrxAC/discord-j2me#3]
While trying to log in, I get this.

![image](https://github.com/gtrxAC/discord-j2me/assets/33337309/ba6c0b1f-c27f-44fc-a181-13026d38a6a6)

This is on [PSPKVM](https://www.gamebrew.org/wiki/PSPKVM), is there a better way for me to debug this? Would be willing to also make a PR if you could point me to some places to tinker as I'm unfamiliar with J2ME :)

**Comment by gtrxAC** [comment]
I'm working on a fix for this, I already made the server list threaded. If you want to help, you can move other code that does HTTP requests to the HTTPThread class, using my latest commit as an example.

**Comment by gtrxAC** [comment]
Do you want to work on this? I'm just asking because I want to release the next version possibly this week (I know a lot of people are waiting for it), and this is one of the last items remaining on my to-do list.

**Comment by e3ndr** [comment]
> Do you want to work on this? I'm just asking because I want to release the next version possibly this week (I know a lot of people are waiting for it), and this is one of the last items remaining on my to-do list.

Apologies for not getting back to you, been pretty busy lately. I would be definitely open to working on the project in the future, but I don't have much time within the short-term to work on it. Sorry!

**Comment by gtrxAC** [comment]
Alright, no worries. I've implemented multi-threading for all HTTP requests - it was actually a bit more work than I thought. Try compiling the latest commit and see if it works on your PSP.

**Comment by e3ndr** [comment]
Getting `Fatal Error: Unable to find package java.lang in classpath or bootclasspath`. Any ideas? I'm trying to compile on Windows if that helps.

![Medal_IRei0k7c7a](https://github.com/gtrxAC/discord-j2me/assets/33337309/c6e85443-1446-42e2-8588-458255241a7d)

**Comment by gtrxAC** [comment]
The build script is not designed to work on Windows - someone else had similar issues with it. Probably need to add something to the (boot)classpath, I just don't know what.

Anyway, here's a compiled version: [discord-j2me.jar.zip](https://github.com/gtrxAC/discord-j2me/files/15340120/discord-j2me.jar.zip) (in a ZIP because of GitHub's upload restrictions)

**Comment by e3ndr** [comment]
> The build script is not designed to work on Windows - someone else had similar issues with it. Probably need to add something to the (boot)classpath, I just don't know what.
> 
> Anyway, here's a compiled version: [discord-j2me.jar.zip](https://github.com/gtrxAC/discord-j2me/files/15340120/discord-j2me.jar.zip) (in a ZIP because of GitHub's upload restrictions)

Got logged in! Have a couple of problems tho:
- When switching to the Direct Messages view, I get `java.lang.NumberFormatException`.
- In server channels, the scroll seems to be messed up.

![Discord_zIPHuSkLtb](https://github.com/gtrxAC/discord-j2me/assets/33337309/7d573c08-967e-490e-8707-daba3311dc08)
![Discord_gJ1jUw3R3z](https://github.com/gtrxAC/discord-j2me/assets/33337309/751bb4b3-c8fe-46b5-9d35-799e07778ff9)

Other than that, solid work! This'll be a great party trick haha.

**Comment by gtrxAC** [comment]
Awesome! I fixed the first problem, but the second problem is probably a quirk of PSPKVM.
