### ISSUE TITLE
Feature suggestion: better dialogs for MAUI devices 

### ISSUE THREAD

**Issue by FurblandChannel** [gtrxAC/discord-j2me#38]
MAUI has standard dialog boxes readily available, which are usually customized to fit the skin better. Dialog boxes on MAUI currently show as full screens with rather clunky navigation. I am unsure if there is a method in J2ME to call these boxes, but I think it is worth a look.

**Comment by gtrxAC** [comment]
I'm fairly certain there is no API for doing this (I've never heard of a MediaTek Java API), but the app now uses custom dialog boxes anyway.
