### ISSUE TITLE
Program hangs on downloading data

### ISSUE THREAD

**Issue by natee22** [gtrxAC/discord-j2me#7]
DEVICE: Palm Zire 72 running PalmOS 5.4

ISSUE: It hangs the entire system after I send out my token and proxy info (I have to hit the reset button on the back)

UPDATE: If I let it sit long enough, it throws a `java.lang.OutOfMemoryError`

**Comment by natee22** [comment]
UPDATE 2: with 1.1.2 it hangs earlier in the process, not even showing the please wait screen

**Comment by MIHAIIIIIIII** [comment]
it means your phone doesnt have enough RAM to run this, i had a similar problem running DOOM RPG on a very old nokia phone

**Comment by shinovon** [comment]
Blocking I/O operations, such as network connection must not be used in lifecycle thread. Creation of separate worker thread is highly recommended.

**Comment by shinovon** [comment]
> Blocking I/O operations, such as network connection must not be used in lifecycle thread. Creation of separate worker thread is highly recommended.

Also related to #3

**Comment by gtrxAC** [comment]
Does the out-of-memory error occur solely due to the blocking IO operation? If so, I'm working on a fix for this (see #3).

**Comment by shinovon** [comment]
> Does the out-of-memory error occur solely due to the blocking IO operation? If so, I'm working on a fix for this (see #3).

Unlikely, OOM may also be caused due system errors

**Comment by gtrxAC** [comment]
@natee22 Try the latest 2.0.0 version.

**Comment by natee22** [comment]
2.0.0 still throws an OOM error, I think the sad 8MB of RAM this device has is too little lol

**Comment by natee22** [comment]
inserting my alt's token, which has much less servers and DMs open, it runs better.

now it crashes on sending messages and sometimes loading the server list (no error)
