### ISSUE TITLE
cant log in

### ISSUE THREAD

**Issue by kristiannowak** [gtrxAC/discord-j2me#9]
i think it might be a data issue since 3g like doesnt exist anymore (the device doesnt have wifi so i have to use data; its the LG GU297 Wink with a Fido (canada) sim card in it; my plan is 4g and the device recognizes it as 3g and texting/calling works fine) 
"javax.microedition.io.ConnectionNotFoundException: the target of the name cannot be found." shows when i try to log in
i dont really know what im doing at all so any help with this would be good

**Comment by sunflowers33d** [comment]
thats not the app's fault, you most likely need to change APN settings for your phone

**Comment by kristiannowak** [comment]
i completely forgot about apn settings but that makes sense
although i set up apn settings and it still doesnt work but another issue is that the apn settings only has "name", "auth type" and "apn" (and username/password when i change the auth type to low or high) as the settings so i cant put all the apn settings that it needs into the phone

**Comment by kristiannowak** [comment]
now it says "java.lang.IllegalArgumentException: Malformed address"

**Comment by gtrxAC** [comment]
Are you sure you didn't change the API URL from the default `http://dsc.uwmpr.online`? Make sure there is no slash at the end (I don't know if that matters).

I don't know what else it could be, other than the carrier not supporting that phone, or your APN settings still being incorrect.

**Comment by AREYsan** [comment]
![FEscr(057)](https://github.com/gtrxAC/discord-j2me/assets/170623095/07daa247-366c-4a12-a460-a1cf1119803d)
![FEscr(056)](https://github.com/gtrxAC/discord-j2me/assets/170623095/0babee4f-e593-4a54-9f8c-4f805c14a194)
The app was working fine until the last update, but after the last update I cannot log in to the app regardless of whether ssl authentication is on or off 
Series 60 version 2 Nokia n70

**Comment by gtrxAC** [comment]
The proxy is offline because it got detected as a "phishing site" by the hosting service. I will either tell you or release an update when it comes back online.
